name: fuel_balance
description: "Fuel balance monitor for pilots"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_local_notifications: ^18.0.1
  wakelock_plus: ^1.2.8
  intl: ^0.20.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
